### ISSUE TITLE
keyword_length ignored

### ISSUE THREAD

**Issue by ranebrown** [hrsh7th/cmp-cmdline#10]
It seems that `keyword_length` is ignored (or misinterpreted) when using a mapping to change buffers.

1. Set `keyword_length = 3`
2. Set mappings below
3. Open 2 files
4. `<leader>n` to switch to next buffer
5. `:` and completion appears immediately

Using `:bn` and then `:` uses the set `keyword_length` prior to triggering completion as expected.

```
nnoremap <silent> <leader>n :bnext<CR>     
nnoremap <silent> <leader>p :bprevious<CR> 
```

**Comment by hrsh7th** [comment]
I think it already fixed by nvim-cmp's side.

**Comment by ranebrown** [comment]
I'm still seeing the issue after updating.

**Comment by hrsh7th** [comment]
I'm organizing issues. I'm closing this for now. Feel free to re-open it.
