### ISSUE TITLE
There is no completion for lua

### ISSUE THREAD

**Issue by stasjok** [hrsh7th/cmp-cmdline#12]
I'm not sure if this is a bug or not, but I don't have any completion for lua after `.`.

Completes:
`:lua `

Doesn't complete:
`:lua vim.`

But `:echo getcompletion("lua vim.", "cmdline")` gives some usefull results. Also I can complete with fallback `<Tab>` (internal completion).

**Comment by hrsh7th** [comment]
Fixed. Thank you.
