### ISSUE TITLE
Does not expand file path

### ISSUE THREAD

**Issue by sparkcanon** [hrsh7th/cmp-cmdline#15]
I am not sure if its just me but `:e %` does not expand `%` into the file path. This extends to something like `:e %:h`.

**Comment by kting28** [comment]
It doesn't work for me either, if cmdline file path completion is enabled, `e %<TAB>` expands to `%_file_path_` , which makes it not very useful as user needs to manually remove the `%` sign. Tab completion of `e %:h` plainly does not work

**Comment by EdmundsEcho** [comment]
Is there a way to have the suggestions only include files once we type `:e `?  I might have a limited imagination, but I can't think of any other source for the autocomplete once it's clear we intend to open a file. Right?

**Comment by tzachar** [comment]
@EdmundsEcho 
Try [cmp-fuzzy-path](https://github.com/tzachar/cmp-fuzzy-path)
