### ISSUE TITLE
Can't handle wildcards

### ISSUE THREAD

**Issue by rafcamlet** [hrsh7th/cmp-cmdline#17]
Using asterisk sign in cmd cause variety of invalid behaviour:
- Sometimes it can't find proper candidates for completion
- It inserts whole record after asterisk, instead of only missing part
![image](https://user-images.githubusercontent.com/8767998/142777551-b8aaa727-b108-424f-9c89-1340bf66881e.png)
- Using double asterisk in path cause major lagging during typing e.g `find ~/project/**/asdf.lua`

Of course, wildcards are redundant with this plugin, but they shouldn't cause errors when people use them because of muscle memory.

**Comment by hrsh7th** [comment]
You don't need wildcard, I think. You just input `nvimvvar` instead.
