### ISSUE TITLE
:help suggestions don't appear with :vert help (or :vertical help)

### ISSUE THREAD

**Issue by Groctel** [hrsh7th/cmp-cmdline#20]
Hi!

First of all thank you very much for your work with cmp! I would send you a merge request fixing this, but I've been reading the code and don't understand how it works :((

The issue I'm having is that completion with `:help <query>` works perfectly but it doesn't work at all with `:vert help <query>`. I guess `vert` could be added as a modifier prefix so that it doesn't affect the rest of the sentence or something like that?

Again, thank you very much for your work!

**Comment by ECon87** [comment]
I have the same issue, but generally. `vertical anycommand` does not work. Also pipes don't work

**Comment by ECon87** [comment]
I wish I had the requisite skills (or time to acquire them)

**Comment by davidscotson** [comment]
Some other commands that take a command  include:

silent, hide, 
things that use + when opening a buffer
as well as the placement and pipes mentioned above.

and hit similar issues

#27 seems to be a duplicate of this specific request about vert help.
