### ISSUE TITLE
incsearch highlight problem

### ISSUE THREAD

**Issue by tzachar** [hrsh7th/cmp-cmdline#29]
Hi.

'incsearch' stopped working for me while using cmdline.
Using the default config from cmp, this is what I get:
[cmp.txt](https://github.com/hrsh7th/cmp-cmdline/files/7837747/cmp.txt)
![Peek 2022-01-10 11-09](https://user-images.githubusercontent.com/4946827/148741587-6fc6cbfe-60c1-462a-bf72-74e4cd6918a6.gif)

**Comment by hrsh7th** [comment]
I think we can't support this.
In my previous investigation, the wilder.nvim has the same problem.

If you have a solution, Please tell me that.

**Comment by tzachar** [comment]
Looking at wilder, it seems they solved the problem.
This also works for cmp:

```diff
diff --git a/lua/cmp/view/custom_entries_view.lua b/lua/cmp/view/custom_entries_view.lua
index d84baee..98aec26 100644
--- a/lua/cmp/view/custom_entries_view.lua
+++ b/lua/cmp/view/custom_entries_view.lua
@@ -177,6 +177,8 @@ custom_entries_view.open = function(self, offset, entries)
   else
     self:_select(0, { behavior = types.cmp.SelectBehavior.Select })
   end
+ local keys = vim.api.nvim_replace_termcodes('<C-R><BS>', true, false, true);
+ vim.api.nvim_feedkeys(keys, 'n', true)
 end
 
 custom_entries_view.close = function(self)
```
Would be better to condition this behaviour on whether the user has incsearch set.


see https://github.com/gelguy/wilder.nvim/pull/65

**Comment by tzachar** [comment]
There is still a flicker though.

**Comment by hrsh7th** [comment]
Thank you for pointing me out it.
Hm... It's a bit problematic with nvim-cmp's text changed detection mechanism.
I'll consider it.
