### ISSUE TITLE
fuzzy searching only work partially.

### ISSUE THREAD

**Issue by jdhao** [hrsh7th/cmp-cmdline#3]
For example, if i type `cls` on the cmdline, `colorscheme` is not in the list of completion items. Do I need to set up in my cmp config or something?

![image](https://user-images.githubusercontent.com/16662357/139097907-8fe59b4f-ced5-4c8d-9165-675bccbb2b77.png)

**Comment by Ddystopia** [comment]
Is it normal that author's "colorscheme" is still not suggested?

**Comment by userrand** [comment]
> Is it normal that author's "colorscheme" is still not suggested?

@Ddystopia When I type :cls I see colorscheme as the 6th item.
