### ISSUE TITLE
Cmdline don't work and don't give completion

### ISSUE THREAD

**Issue by melsiir** [hrsh7th/cmp-cmdline#30]
I tried to install cmdline but it just don't give any suggestions or completion

Here is my config using packer :

   use({
     "hrsh7th/cmp-cmdline",
     config = "require('custom.plugins.cmdline')",
   })

The cmdline config :

require'cmp'.setup.cmdline(':', {
  sources = {
    { name = 'cmdline' }
  }
})

**Comment by hrsh7th** [comment]
Did you install nvim-cmp itself?

**Comment by melsiir** [comment]
It working now

**Comment by melsiir** [comment]
First It work fine but now I am getting this weird long error and all my plugins get disabled




Error in packer_compiled: ...x/files/home/.config/
nvim/lua/custom/plugins/cmdline.lua:1: module 'cmp' not found:^@^Ino field package.preload['cmp']^@^
Ino file './cmp.lua'^@^Ino file '/data/data/com.termux/files/usr/share/luajit-2.1.0-beta3/cmp.lua'^@^Ino file '/usr/local/share/lua/5.1/cmp.lua'^@^Ino file '/usr/local/share/lua/5.1/cmp/init.lua'^@^Ino file '/data/data/com.termux/files/usr/share/lua/
5.1/cmp.lua'^@^Ino file '/data/data/com.termux/files/usr/share/lua/5.1/cmp/init.lua'^@^Ino file '/data/data/com.termux/files/home/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/cmp.lua'^@^Ino
file '/data/data/com.termux/files/home/.cache/nvim
/packer_hererocks/2.1.0-beta3/share/lua/5.1/cmp/in
it.lua'^@^Ino file '/data/data/com.termux/files/home/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lu
arocks/rocks-5.1/cmp.lua'^@^Ino file

**Comment by melsiir** [comment]
My cmp plugin is lazy loaded after other plugin so when they are not loaded I got the error above
