### ISSUE TITLE
Feature Request: display current value when command starts with :set <settingname>

### ISSUE THREAD

**Issue by davidscotson** [hrsh7th/cmp-cmdline#32]
Using `:set <partialsearch>`  gives setting names as completion options.

Would it be possible to also add the current value as a 'preview', basically whatever `:set name?` would tell you.

**Comment by hrsh7th** [comment]
I think it's already can...? (In my environment, `:set virtualedit=|` will only show the completion item that `virtualedit=all`.

**Comment by davidscotson** [comment]
Once you get to the other side of the = it will autocomplete non-boolean values, but I was thinking something more like this screenshot (from the tridactyl vim-like browser):
<img width="1186" alt="Screenshot 2022-02-13 at 21 01 56" src="https://user-images.githubusercontent.com/7288187/153774965-b73cdf83-a09a-4dae-85cb-218a290d2706.png">

Where, after you type set<space> it starts to show you the list of settings that match the text typed so far, but also shows the current value for that setting (it also shows possible setting values or their js type and a help string). I found it helpful to add context to the settings when you're not quite sure what you are looking for, similar to when a file shows a preview.
