### ISSUE TITLE
Unable to confirm selection with nvim's default mappings

### ISSUE THREAD

**Issue by grezp** [hrsh7th/cmp-cmdline#36]
All other default mappings work as expected. For example, `<C-n>` for next, `<C-p>`  for previous, `<C-e>` to close.

However, `<C-y>` to confirm does not work on either command mode or while searching. It places a `^Y` char.

Creating a mapping config does not work:

```
mapping = {
  ['<C-y>'] = cmp.mapping.confirm({ select = true }),
}
```

How can I enable this?

**Comment by gegoune** [comment]
It works for me, I do set it up in main `cmp.setup({})`, like that:

```lua
cmp.setup({
  mapping = {
      ['<C-y>'] = cmp.mapping(cmp.mapping.confirm { select = true }, { 'i', 'c' }),
  }
})
```
