### ISSUE TITLE
Group index - does not seem to work

### ISSUE THREAD

**Issue by JoseConseco** [hrsh7th/cmp-cmdline#40]
According to docs following setup
cmdline => group_index = 1
cmdline_history => 2

Then if `cmdline` outputs any results, then `cmdline_history` results should get ignored. But it does not seem to work in cmp-cmdline. My setup:
```lua
cmp.setup.cmdline(":", {
  formatting = {
    format = function(entry, vim_item)
      vim_item.kind = lspkind.presets.default[vim_item.kind] .. " " .. vim_item.kind
      vim_item.abbr = vim.fn.strcharpart(vim_item.abbr, 0, 50) -- hack to clamp cmp-cmdline-history len
      vim_item.menu = ({
        cmdline_history = "[HIST]",
        cmdline = "[CMD]",
        fuzzy_path = "[PATH]",
        buffer = "[BUFF]",
      })[entry.source.name]
      return vim_item
    end,
  },
  sources = cmp.config.sources {
    { name = "cmdline_history", priority = 2, group_index=2 },
    { name = "cmdline", priority = 2, group_index=1 },
    { name = "fuzzy_path", priority = 1, group_index=2 }, -- from tzacher
    { name = "buffer", priority = 1, group_index=2 },
  },
})  
```

Then I try to enter :  
  :PackerSync   -> and cmp shows  `cmd_history` elements first,  then `cmdline` results.

Expected:
`cmdline` result first,  no `cmd_histoyr` since it is group 2

**Comment by gegoune** [comment]
This was fixed upstream: https://github.com/dmitmel/cmp-cmdline-history/issues/3.

**Comment by JoseConseco** [comment]
@gegoune I do not see any difference after update. Maybe my config (posted above) is wrong? Can you share yours?

**Comment by hrsh7th** [comment]
I can see the correct result with the following config.

```lua
  cmp.setup.cmdline(':', {
    mapping = cmp.mapping.preset.cmdline(),
    sources = {
      { name = 'cmdline', group_index = 1, },
      { name = 'cmdline_history', group_index = 2 },
    },
  })
```

**Comment by max397574** [comment]
works for me as well

**Comment by JoseConseco** [comment]
Ok, my bad. I think I had old config. Wrong:
`sources = cmp.config.sources {`
Good: 
`sources =  {`
Now it works! Thx.

**Comment by hrsh7th** [comment]
The `cmp.config.sources` is shorthand helper.

```
sources = cmp.config.sources({
  { name = 'cmdline' }
}, {
  { name = 'cmdline_history' }
})
```

is equivant to

```
sources = {
  { name = 'cmdline', group_index = 1 },
  { name = 'cmdline_history' }
}
```
