### ISSUE TITLE
Disable completion if the command starts with a number

### ISSUE THREAD

**Issue by mercxry** [hrsh7th/cmp-cmdline#45]
Hi, I would like to disable completion when the command is a number, this is a problem for me because when I want to jump to a specific line a wall of completion text appears exactly where I want to look and doesn't allow me to peek the line before jumping.

<img width="630" alt="Screen Shot 2022-04-26 at 13 37 04" src="https://user-images.githubusercontent.com/39272153/165291689-9ce23ed9-65f0-4dfd-ab41-150862e47224.png">

**Comment by hrsh7th** [comment]
It's expected but I can understand your expectation...

For example, `1delete` should be completed... Hm...

**Comment by mercxry** [comment]
I was thinking that if the command it's just a number it doesn't complete, but as soon as you add a letter it start the completions, for example `:42` doesn't show anything, but `:42d` should start show the completion menu.

Do you think this is a good solution to the problem?

**Comment by hrsh7th** [comment]
I think now cmp-cmdline behaves the above explanation.

**Comment by mercxry** [comment]
It does, thank you! 🙇‍♂️

**Comment by hrsh7th** [comment]
PR welcome.
