### ISSUE TITLE
Error when substituting \( or \)

### ISSUE THREAD

**Issue by saulaxel** [hrsh7th/cmp-cmdline#53]
I'm trying to substitute `\(` by using the following command

    :s/\\(/<something>

But, in the same moment I write the left parent `(`, it shows the error "\\( sin complemento", which in English would be something like "not pair found for \\(" or "no complement for \\(" , which seems to suggest that things are not being escaped properly at some point or maybe they are being escaped twice.

Here's the full traceback:

    Error executing vim.schedule lua callback: Vim:E54: \( sin complemento
    stack traceback:
            [C]: in function 'getcompletion'
            ...e/pack/packer/start/cmp-cmdline/lua/cmp_cmdline/init.lua:64: in function 'exec'
            ...e/pack/packer/start/cmp-cmdline/lua/cmpcmdline/init.lua:115: in function 'complete'
            .../re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:288: in function 'complete'
            .../re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:170: in function 'autoindent'
            .../re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:162: in function 'on_change'
            .../re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/init.lua:301: in function 'callback'
            .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:122: in function <.../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:120>

**Comment by Xein234** [comment]
It seems that `getcompletion()` is interpreting `\\` as a single `\`, and thus it interprets `\\(` as the regex metacharacter `\(` that is used for grouping. So we can properly escape slashes by replacing each `\\` by `\\\\` before calling it. I did that and is no longer throwing that error.
