### ISSUE TITLE
unavailable source names

### ISSUE THREAD

**Issue by Ruixi-rebirth** [hrsh7th/cmp-cmdline#63]
![image](https://user-images.githubusercontent.com/75824585/190579727-e140c385-b6d5-44b8-ad01-f4375ccfbba6.png)

**Comment by hrsh7th** [comment]
It seems you specify the `cmdline` source even if you didn't install `cmdline` source.

**Comment by Ruixi-rebirth** [comment]
![image](https://user-images.githubusercontent.com/75824585/190614815-424d0e28-8aab-4d3e-9ea2-e528e9561075.png)

**Comment by hrsh7th** [comment]
Please provide the detailed information.
You don't even provide the your configuration.
