### ISSUE TITLE
Error detected while processing TextChangedI Autocommands for "*"

### ISSUE THREAD

**Issue by laduygaga** [hrsh7th/cmp-cmdline#77]
Error when i type `start with "*"`

https://user-images.githubusercontent.com/23116211/209682546-b8ba7d3d-8bc1-455f-a4cb-8621a489824d.mp4

**Comment by hrsh7th** [comment]
I can't understand.

**Comment by PrimeO7** [comment]
This happened to me aswell, the error comes up more often with greater linecount. I wasn't able to isolate what exactly the issue is, if it's my config or something else.

I just removed cmp-cmdline as a dependency for nvim-cmp and the error is gone.
