### ISSUE TITLE
New `statuscolumn` option modifies the cmdline popup

### ISSUE THREAD

**Issue by mcauley-penney** [hrsh7th/cmp-cmdline#78]
Nightly just merged the [statuscolumn option](https://github.com/neovim/neovim/pull/20621), allowing users to customize the gutter and line number columns. I found that, at least with the settings I'm currently using for the statuscolumn, the cmp-cmdline popup window is modified and, in this particular case, runs off the right of the popup. 

In the below GIF, I use the cmdline popup before the `statuscolumn` option is set and then after. Before, you can see proper functioning but, after, line numbers appear, the type of the item in the list runs off the edge, etc. It appears to adopt whatever settings are given for statuscolumn. 

![statuscolumn_cmp-cmdline](https://user-images.githubusercontent.com/59481467/211600984-fb48ef28-3172-497d-94f1-25d5dcbcfd59.gif)

**Comment by gegoune** [comment]
Update your nvim - it has been fixed upstream.

**Comment by hrsh7th** [comment]
@gegoune Thanks. I'll update my neovim in my local environment.

**Comment by mcauley-penney** [comment]
> Update your nvim - it has been fixed upstream.

Thank you, I wasn't aware and appreciate the correction!
