### ISSUE TITLE
Variable type?

### ISSUE THREAD

**Issue by windowsrefund** [hrsh7th/cmp-cmdline#95]
This doesn't look correct? 

![Screenshot_2023-05-21_01-56-01](https://github.com/hrsh7th/cmp-cmdline/assets/512222/7829b47f-7b94-461a-8ab9-44e86fcddf9d)

**Comment by fmoda3** [comment]
I have the same problem.  After trying various commits, looks like this one broke it: https://github.com/hrsh7th/cmp-cmdline/commit/d8738f0104a8e2fd71e7e0ecef229423107fa11a

<img width="393" alt="image" src="https://github.com/hrsh7th/cmp-cmdline/assets/1746471/a30ad837-4eca-434a-9cd8-9a89328e07d2">

**Comment by JKubovy** [comment]
I've got same problem.

**Comment by fmoda3** [comment]
@uga-rosa @hrsh7th Any chance we can revert https://github.com/hrsh7th/cmp-cmdline/commit/d8738f0104a8e2fd71e7e0ecef229423107fa11a to fix this issue?

**Comment by uga-rosa** [comment]
What makes it VARIABLE is that it is defined as such.
https://github.com/hrsh7th/cmp-cmdline/blob/5af1bb7d722ef8a96658f01d6eb219c4cf746b32/lua/cmp_cmdline/init.lua#L72
What does this revert mean? The number that comes right after the `:` represents a range, and it would be correct to line up a command that can take a range (`:h :range`).

**Comment by fmoda3** [comment]
I goto line all the time with `:150` as an example, which used to work fine, but now creates a very incorrect completion list like you can see above.  Perhaps reverting isnt the right solution, but that commit _did_ break something (as seen in the images above).  Note the first image too, where it happens with non-number prefixes.  I've pinned my plugin to the commit prior to this, but would prefer not to do that, if there is an appropriate fix.

**Comment by uga-rosa** [comment]
It is true that there are some commands out there that do not allow range, but it is correct in itself that the command is completed with `:{number}`. For example, `:1w` is a formal command.
And isn't this issue a report that the kind is `variable`? I explained in my earlier reply that that is the spec.

**Comment by uga-rosa** [comment]
I have no idea what you think the problem is, or how reverting back to before that commit will fix it. I can't reply any further if you don't explain it to me in detail from scratch. You and I do not share the same premise.

**Comment by fmoda3** [comment]
Here's how it worked before https://github.com/hrsh7th/cmp-cmdline/commit/d8738f0104a8e2fd71e7e0ecef229423107fa11a:

typing _just_ `:150` shows no completions yet:
<img width="1030" alt="image" src="https://github.com/hrsh7th/cmp-cmdline/assets/1746471/5150aaf7-431e-41ba-9703-67b8fad94c42">

_then_ when you type another character, it starts to complete:
<img width="1027" alt="image" src="https://github.com/hrsh7th/cmp-cmdline/assets/1746471/a8264561-1b0f-463f-9c65-012ab1b93fcb">

but now typing _just_ `:150` shows a huge list:
<img width="1020" alt="image" src="https://github.com/hrsh7th/cmp-cmdline/assets/1746471/d5e6a34e-75bb-4e1f-ad1b-865122a907a0">

while I understand that the large list in the second _technically_ is correct in that its showing _every possible_ completion, I would argue that the previous behavior was more useful.  Similarly, if i just type `:` it doesn't show me _everything_ i can complete with yet, it waits until i have one character to start completing.  The way numbers complete now, feels equivalent to just showing me every possible command right off the bat.  At least I think having the option to complete using the old behavior should be made available.

**Comment by fmoda3** [comment]
ah, i think my issue is different that the one from the original poster (when i originally thought it was the same).  I can move it to its own issue, though i don't think i can move the discussion.

**Comment by uga-rosa** [comment]
Let's make another issue.

**Comment by windowsrefund** [comment]
I can no longer reproduce this and assume a recent update must be responsible for the fix.

**Comment by windowsrefund** [comment]
The original issue is back now that I've updated to commit 8ee981b4a91f536f52add291594e89fb6645e451

**Comment by hrsh7th** [comment]
Please create new issue.

The `Variable type` issue is not a valid issue.
